class ItemsController < ApplicationController

  before_action :authenticate_user!

  def create

#1 we call Item.new to create a new instance of Item
    # @item = Item.new
    # @item.name = params[:item][:name]
    # @item.user = current_user

    @item = current_user.items.new(item_params)

#1 If saved the user will be redirected to the route generated by @item. Redirecting to @item will direct the user to the items show view.
    if @item.save
      flash[:notice] = "Item saved!"     
    else
      flash[:error] = "Item not saved!"
    end

    redirect_to current_user

  end

  def destroy

    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "\"#{@item}\" was deleted successuflly."
    else
      flash[:error] = "There was an error deleting that item."
    end

    respond_to do |format|
      format.html
      format.js
    end


  end

  private 

  def item_params
  	params.require(:item).permit(:name)
  end
end