class ItemsController < ApplicationController

<<<<<<< HEAD
  before_action :authenticate_user!


  def create

#1 we call Item.new to create a new instance of Item
    # @item = Item.new
    # @item.name = params[:item][:name]
    # @item.user = current_user

    @item = current_user.items.new(item_params)

#1 If saved the user will be redirected to the route generated by @item. Redirecting to current_user will direct the user to the users show view.
    if @item.save
      flash[:notice] = "Item saved!"     
    else
      flash[:error] = "Item not saved!"
    end

    redirect_to current_user

=======
def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create

    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to root_path
    else
      flash [:error] = "There was an error saving the item to the list. Please try again."
      render :new
    end

>>>>>>> 4457d879934592ba85110f87b329e1274213838a
  end

  def destroy

<<<<<<< HEAD
#2 searches for specific item to be deleted
=======
>>>>>>> 4457d879934592ba85110f87b329e1274213838a
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:notice] = "\"#{@item}\" was deleted successuflly."
<<<<<<< HEAD
    else
      flash[:error] = "There was an error deleting that item."
    end
#2 redirects to 
    respond_to do |format|
      format.html
      format.js
    end


  end

  private 

  def item_params
  	params.require(:item).permit(:name)
  end
end
=======
      redirect_to root_path
    else
      flash[:error] = "There was an error deleting that item."
      redirect_to root_path
    end

  end

end
>>>>>>> 4457d879934592ba85110f87b329e1274213838a
